[2024-07-25 17:51:57,465] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: send_stock_data.send_data scheduled__2024-07-25T17:50:00+00:00 [queued]>
[2024-07-25 17:51:57,471] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: send_stock_data.send_data scheduled__2024-07-25T17:50:00+00:00 [queued]>
[2024-07-25 17:51:57,471] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-07-25 17:51:57,472] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2024-07-25 17:51:57,472] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-07-25 17:51:57,483] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): send_data> on 2024-07-25 17:50:00+00:00
[2024-07-25 17:51:57,486] {standard_task_runner.py:52} INFO - Started process 670 to run task
[2024-07-25 17:51:57,488] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'send_stock_data', 'send_data', 'scheduled__2024-07-25T17:50:00+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/***_stream.py', '--cfg-path', '/tmp/tmp2drpsnen', '--error-file', '/tmp/tmp9vpho27r']
[2024-07-25 17:51:57,489] {standard_task_runner.py:80} INFO - Job 33: Subtask send_data
[2024-07-25 17:51:57,500] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.10/site-packages/***/configuration.py:528 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-07-25 17:51:57,532] {task_command.py:371} INFO - Running <TaskInstance: send_stock_data.send_data scheduled__2024-07-25T17:50:00+00:00 [running]> on host 3375e7ece4d4
[2024-07-25 17:51:57,580] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=send_stock_data
AIRFLOW_CTX_TASK_ID=send_data
AIRFLOW_CTX_EXECUTION_DATE=2024-07-25T17:50:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-07-25T17:50:00+00:00
[2024-07-25 17:51:57,582] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-07-25 17:51:57,582] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2024-07-25 17:51:57,582] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2024-07-25 17:51:57,582] {conn.py:919} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-07-25 17:51:57,631] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-07-25 17:51:57,632] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2024-07-25 17:51:57,632] {conn.py:919} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-07-25 17:51:57,681] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2024-07-25 17:51:57,682] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2024-07-25 17:51:57,682] {conn.py:919} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-07-25 17:51:57,683] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/airflow_stream.py", line 38, in send_data
    producer = KafkaProducer(
  File "/home/airflow/.local/lib/python3.10/site-packages/kafka/producer/kafka.py", line 381, in __init__
    client = KafkaClient(metrics=self._metrics, metric_group_prefix='producer',
  File "/home/airflow/.local/lib/python3.10/site-packages/kafka/client_async.py", line 244, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/airflow/.local/lib/python3.10/site-packages/kafka/client_async.py", line 900, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2024-07-25 17:51:57,691] {taskinstance.py:1415} INFO - Marking task as FAILED. dag_id=send_stock_data, task_id=send_data, execution_date=20240725T175000, start_date=20240725T175157, end_date=20240725T175157
[2024-07-25 17:51:57,699] {standard_task_runner.py:92} ERROR - Failed to execute job 33 for task send_data (NoBrokersAvailable; 670)
[2024-07-25 17:51:57,741] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-07-25 17:51:57,763] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
