[2024-08-07T02:23:59.515+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-07T02:23:59.548+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: send_stock_data.format_data manual__2024-08-07T02:16:07.593684+00:00 [queued]>
[2024-08-07T02:23:59.557+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: send_stock_data.format_data manual__2024-08-07T02:16:07.593684+00:00 [queued]>
[2024-08-07T02:23:59.558+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-08-07T02:23:59.576+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): format_data> on 2024-08-07 02:16:07.593684+00:00
[2024-08-07T02:23:59.586+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=632) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-07T02:23:59.586+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'send_stock_data', 'format_data', 'manual__2024-08-07T02:16:07.593684+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/***_stream.py', '--cfg-path', '/tmp/tmpi46imnng']
[2024-08-07T02:23:59.588+0000] {standard_task_runner.py:64} INFO - Started process 643 to run task
[2024-08-07T02:23:59.588+0000] {standard_task_runner.py:91} INFO - Job 52: Subtask format_data
[2024-08-07T02:23:59.609+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-08-07T02:23:59.651+0000] {task_command.py:426} INFO - Running <TaskInstance: send_stock_data.format_data manual__2024-08-07T02:16:07.593684+00:00 [running]> on host 7290ddab538a
[2024-08-07T02:23:59.753+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='send_stock_data' AIRFLOW_CTX_TASK_ID='format_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-07T02:16:07.593684+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-07T02:16:07.593684+00:00'
[2024-08-07T02:23:59.754+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-07T02:23:59.899+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-07T02:23:59.900+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_stream.py", line 53, in format_data
    formatted_data[symbol] = []
    ~~~~~~~~~~~~~~^^^^^^^^
TypeError: list indices must be integers or slices, not str
[2024-08-07T02:23:59.912+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=send_stock_data, task_id=format_data, run_id=manual__2024-08-07T02:16:07.593684+00:00, execution_date=20240807T021607, start_date=20240807T022359, end_date=20240807T022359
[2024-08-07T02:23:59.925+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 52 for task format_data (list indices must be integers or slices, not str; 643)
[2024-08-07T02:23:59.967+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-07T02:23:59.990+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-07T02:23:59.997+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
